### ISSUE TITLE
Issues in installing CDN Caching Helm Chart

### ISSUE THREAD

**Issue by arpit6070** [open-ness/edgeapps#21]
<img width="760" alt="nginx" src="https://user-images.githubusercontent.com/66903089/87655081-66526b80-c775-11ea-8142-2749ad66dc41.PNG">

**Comment by archie95** [comment]
Hi @amr-mokhtar ,
We found the solution to this issue. The problem is that in the example given (https://github.com/open-ness/edgeapps/tree/openness-20.06/applications/cdn-caching/nginx) the release name is taken as **openness_cdn**. We can't use underscore in release name. Rather we should either use '-' or keep it one word only all in small letters.
------------------------------------------------------------------------------------------------------------------------------

helm install -f <path-to-optional-user-values-file> --set-file nginx.http.server.ssl_cert_file=<path-to-certificate-file> --set-file nginx.http.server.ssl_key_file=<path-to-key-file> <release-name> <path-to-helm-chart>

**helm install -f ./examples/sriov_nginx_values.yaml  --set-file nginx.http.server.ssl_cert_file=$PWD/nginx.crt --set-file nginx.http.server.ssl_key_file=$PWD/nginx.key opennesscdn ./helm/**


@cjnolan Request you to please make the necessary changes in the document. Thanks.

Regards,
Archit

**Comment by amr-mokhtar** [comment]
Agree. this is a typo in the readme. You can use `openness-cdn` instead.

**Comment by amr-mokhtar** [comment]
The corresponding doc has been updated as part of PR: https://github.com/open-ness/edgeapps/pull/23
